spring:
  datasource:
    dubbo-provider:
      jdbc-url: jdbc:mysql://localhost:3306/dubbo-provider?useUnicode=true&characterEncoding=utf8
      driverClassName: com.mysql.jdbc.Driver
      username: root
      password: root
  resources:
    static-locations: file:///D:/static
  dubbo:
    application:
      registry: zookeeper://192.168.0.110:2181

server:
  port: 8084

system:
  upload:
    path: D:/static

